#!/bin/bash

# this bash file will set a number runs for the number of times to run 01-run.sh.
# It will save the run number is input_tracking.txt which is set up in a csv format.
# It will save the run number so that the rest of the params can be written on the same line
# by set_params.py (which writes the rest of the params). This should be the
# structure of the input_tracking.txt file: run, xign,yign,fuel,slp,asp,ws,wd,m1,m10,m100,cc,ch,cbh,cbd,lhc,lwc
# The first line is the header, and the rest of the lines are the runs.
# After writing the number, the script will call set_params.py to write the rest of the parameters
# and to set the parameters in elmfire.data.in and 01-run.sh. Then, it will call 01-run.sh to run the simulation.
# It will then create a directory in ./cases called ./case_{run} and move the inputs and outputs folders
# that are generated by 01-run.sh as ./inputs and ./outputs in that directory.

if [ -z "$1" ]; then
    echo "Usage: $0 <number_of_runs>"
    exit 1
fi

NUM_RUNS=$1
RUN_DIR="./cases"
NONZERO_START=0

# get a starting run number from command line arguments
if [ -z "$2" ]; then
    START_RUN=0  # Default starting run number
else
    echo "START RUN: $2"
    START_RUN=$2
fi

if [[ "$START_RUN" -eq 0 ]]; then
    echo "CLEAR CASES AND SIMS"
    rm -rf $RUN_DIR/*
    rm -rf ./processed_sims/*
    echo "RESET INPUT AND FIRE AREA TRACKING FILES"
    # replace input_tracking.txt with the header from the config file
    echo "run,xign,yign,ws,wd,m1,m10,m100,lhc,lwc,firearea" > ./configuration/input_tracking.txt
    rm ../fire_area_most_recent_run.txt
    touch ../fire_area_most_recent_run.txt
else
    echo "STARTING FROM RUN: $START_RUN"
    NONZERO_START=1
fi

mkdir -p $RUN_DIR

# start a timer for speed testing
START_TIME=$(date +%s)

for (( run=START_RUN; run<NUM_RUNS+START_RUN; run++ )); do

    echo "Running simulation for run number: $run"
    # Call set_params.py to set the parameters
    python3 ./configuration/set_params.py $run $NONZERO_START
    bash 01-run.sh
    
    # Create a directory for this run and move inputs and outputs
    RUN_CASE_DIR="$RUN_DIR/case_$run"
    mkdir -p $RUN_CASE_DIR
    mv outputs/* $RUN_CASE_DIR/
    mv inputs $RUN_CASE_DIR/
    
done

# End of runs
# End timer and calculate duration
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))
# send time to ./output_check/timings.csv, directory already made
echo "elmfire duration: $DURATION (s)" > ./output_check/timings.csv
